# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
    - run: cd src/pocket_note && flutter --disable-analytics  
    - run: cd src/pocket_note && flutter test
    - run: cd src/pocket_note && dart run build_runner build --delete-conflicting-outputs 
    - run: cd src/pocket_note && flutter build apk

    - run: cd src/pocket_note && flutter build appbundle
