# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        
    - working-directory: ./src/pocket_note
    - run: flutter pub get

    - working-directory: ./src/pocket_note
    - run: flutter test

    - working-directory: ./src/pocket_note
    - run: flutter build apk

    - working-directory: ./src/pocket_note
    - run: flutter build appbundle
